const LISTITEM = {
	Botnet : 'Malicious software that blocks access to a system until a ransom is paid. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod',
 	Cloud : 'From my years of teaching, I am confident to say that it is', 
 	DDoS: 'Roven way to learn and speak English ',
 	Domain:'Christopher Hill, the international ESL professor (with 20+ years of exp',
 	Endpoint:'A lot of students have studied English for years but still ',
 	Exploit:'Speak English on an advanced level. They have tried many methods, attend',
 	Firewall:'Chrisn way to learn and speak English',
	Malware:'From my years of teaching, I am confident to say that it is',
	Penetration:'Malicious software that blocks access to a system until a ransom is paid. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod',
	Test:'Speak English on an advanced level. They have tried many methods, attend',
	'Phishing/ Spearphishing':'Christopher Hill, the international ESL professor (with 20+ years of exp',
	Ransomware:'From my years of teaching, I am confident to say that it is',
	Session:'From my years of teaching, I am confident to say that it is',
	Hijacking:'Malicious software that blocks access to a system until a ransom is paid. Lorem ipsum dolor sit amet, consectetur',
	Social:'Speak English on an advanced level. They have tried many methods, attend',
	Engineering:'Christopher Hill, the international ESL professor (with 20+ years of exp',
	Software:'Aren’t able to ing classes, learning how to pronounce every single word and even getting a private Englis',
	SOC:'In this book, erience) will show you powerful unique ways to rapidly improve your spoken English. With',
	Trojan:'Ttopics you already have interest in, you will find out how easy and effortless to learn and speak fluent English. This',
	Horse:	'Ffective method is simple, yet powerful. You will able to learn and improve your spoken English three to five tim',
	VPN:'To improve their spoken English, yet they still have a hard time pronouncing English words correctly or feeling',
	Virus:'Easy for an English learner to go from a beginner English level to an intermediate English level. However, it takes',
	Worm :'More time to go from an Intermediate level to an advanced English level.'
}